name: ecommerce static website
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v4
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: List files
        run: |
         pwd
         ls -R
      - name: upload to s3 bucket
        run: |
          aws s3 cp ecomm-2.1/img/ s3://github-actions001/ --recursive \
          aws s3 sync ecomm-2.1/ s3://github-actions001/ \
          --exclude "*" \
          --include "index.html"
          