name: build and deploy
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  CLONE:
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v4
  CONFIGURE:
    runs-on: ubuntu-latest
    steps:
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: building static website
        if: github.head_ref == 'feature' && (github.actor == 'ashishaluwala-25' || github.actor == 'vasanth')
        run: aws s3 sync /ecomm-2.1/ s3://static-ecommerce-website 
